### ISSUE TITLE
Mutex failure in Thread.park

### ISSUE THREAD

**Issue by dgrove-oss** [qbicc/qbicc#1213]
From Zulip discussion.
Test program:
```
public class Sleep {
    public static void main(String[] args) {
        System.out.println("Yawn...");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException t) {}
        System.out.println("...I'm awake");
    }
}
```

```
Daves-MacBook-Pro-2:tests dgrove$ /tmp/output/a.out 
Yawn...
Exception in thread "main" java.lang.InternalError: mutex operation failed
	at java.lang.Throwable.fillInStackTrace(Throwable.java:798)
	at java.lang.Throwable.<init>(Throwable.java:271)
	at java.lang.Error.<init>(Error.java:71)
	at java.lang.VirtualMachineError.<init>(VirtualMachineError.java:54)
	at java.lang.InternalError.<init>(InternalError.java:51)
	at java.lang.Thread.park(Thread$_patch.java:227)
	at jdk.internal.misc.Unsafe.park(UnsafeParkUnpark.java:48)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
	at java.lang.Thread.sleep(Thread$_patch.java:156)
	at java.lang.Thread.sleep(Thread$_native.java:62)
	at Sleep.main(Sleep.java:5)
```

**Comment by dgrove-oss** [comment]
More data.  The crash only happens if the Sleep is performed on the main thread.  A program like this is fine:
```
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class HelloWorldExecutor {
    public static void main(String[] args) {
        ExecutorService e = Executors.newSingleThreadExecutor();
        e.submit(HelloWorldExecutor::run);
        e.shutdown();
    }

    static void run() {
        System.out.println("Yawn...");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException t) {} catch (Throwable t2) { System.err.println("WHOOPS"); }
        System.out.println("...I'm awake");
    }
}
```

Strong indication that the problem is incompleteness of our intrinsic + special constructor that fakes up a java.lang.Thread instance to use for the main thread during boot.
