### ISSUE TITLE
Assertion error from Bootstrap method (string concatenation)

### ISSUE THREAD

**Issue by dgrove-oss** [qbicc/qbicc#1266]
Ran into this when writing small test programs for #1265.

The small program below fails at runtime because there is an assertion error evaluating the bootstrap method for the invokedynamic in string concatenation. 

```
public class HelloWorld2 {
    public static void main(String[] args) {
        System.out.println("Hi from "+HelloWorld.class.getName()+"!");
    }
}
```
Generated byte code
```
  public static void main(java.lang.String[]);
    Code:
       0: getstatic     #7                  // Field java/lang/System.out:Ljava/io/PrintStream;
       3: ldc           #13                 // class HelloWorld
       5: invokevirtual #15                 // Method java/lang/Class.getName:()Ljava/lang/String;
       8: invokedynamic #21,  0             // InvokeDynamic #0:makeConcatWithConstants:(Ljava/lang/String;)Ljava/lang/String;
      13: invokevirtual #25                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
      16: return

```
Backtrace on executing:
```
Daves-MacBook-Pro-2:tests dgrove$ /tmp/output/a.out 
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.AssertionError
	at java.lang.Throwable.fillInStackTrace(Throwable.java:798)
	at java.lang.Throwable.<init>(Throwable.java:271)
	at java.lang.Error.<init>(Error.java:71)
	at java.lang.LinkageError.<init>(LinkageError.java:55)
	at java.lang.BootstrapMethodError.<init>(BootstrapMethodError.java:82)
	at HelloWorld2.main(HelloWorld2.java:3)
The uncaught exception handler threw an exception or error
```

**Comment by dgrove-oss** [comment]
Looking into this some more. This is the assertion in ClassSpecializaer.java that is tripping:
```
       private List<MethodHandle> findGetters(Class<?> speciesCode, List<Class<?>> types) {
            MethodHandle[] mhs = new MethodHandle[types.size()];
            for (int i = 0; i < mhs.length; ++i) {
                mhs[i] = findGetter(speciesCode, types, i);
                assert(mhs[i].internalMemberName().getDeclaringClass() == speciesCode);
            }
            return List.of(mhs);
        }
```
Inspecting the build-time objects in the debugger, it appears that we have managed to create two VmClassImpl instances for the same LoadedTypeDefinition (`BMH$Species_LL`).

**Comment by dgrove-oss** [comment]
This change gets by the immediate AssertionError and results in the VmClassImpl instance only being created once, but we trip another assertion shortly later in the BoundMethodHandleConstructor because `speciesData()` returns `null`.  So either the fix is not correct, or there are more things going wrong in this code path...
```
diff --git a/interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java b/interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
index 87734100..f0979cdf 100644
--- a/interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
+++ b/interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
@@ -123,9 +123,7 @@ final class VmClassLoaderImpl extends VmObjectImpl implements VmClassLoader {
         }
         LoadedTypeDefinition loaded = defined.load();
         VmClassImpl vmClass = createVmClass(vm, loaded, hidden);
-        if (hidden) {
-            loaded.setVmClass(vmClass);
-        }
+        loaded.setVmClass(vmClass);
         if (! hidden && this.defined.putIfAbsent(internalName, vmClass) != null) {
             VmThrowable throwable = vm.noClassDefFoundErrorClass.newInstance("Class already defined");
             VmThreadImpl thread = (VmThreadImpl) Vm.requireCurrentThread();
```

**Comment by dgrove-oss** [comment]
#1288 fixed a couple more things.

**Comment by dgrove-oss** [comment]
After https://github.com/qbicc/qbicc-class-library/pull/196 and #1291 and #1294 this finally works!
