### ISSUE TITLE
Missing CmpAndSwap implementation in DotNodeVisitor

### ISSUE THREAD

**Issue by galderz** [qbicc/qbicc#629]
When running with `--gen-graph`:

```
[E] (org.qbicc.driver) ADD: An exception was thrown in an element handler: java.lang.IllegalStateException: Visitor for node class org.qbicc.graph.CmpAndSwap is not implemented
	at org.qbicc.plugin.dot.DotNodeVisitor.visitUnknown(DotNodeVisitor.java:217)
	at org.qbicc.plugin.dot.DotNodeVisitor.visitUnknown(DotNodeVisitor.java:139)
	at org.qbicc.graph.ValueVisitor.visit(ValueVisitor.java:93)
	at org.qbicc.graph.CmpAndSwap.accept(CmpAndSwap.java:125)
	at org.qbicc.plugin.dot.DotNodeVisitor.getNodeName(DotNodeVisitor.java:1483)
	at org.qbicc.plugin.dot.DotNodeVisitor.getNodeName(DotNodeVisitor.java:1461)
	at org.qbicc.plugin.dot.DotNodeVisitor.processDependency(DotNodeVisitor.java:1359)
	at org.qbicc.plugin.dot.DotNodeVisitor.visit(DotNodeVisitor.java:580)
	at org.qbicc.plugin.dot.DotNodeVisitor.visit(DotNodeVisitor.java:139)
	at org.qbicc.graph.If.accept(If.java:86)
	at org.qbicc.plugin.dot.DotNodeVisitor.getNodeName(DotNodeVisitor.java:1499)
	at org.qbicc.plugin.dot.DotNodeVisitor.process(DotNodeVisitor.java:1578)
	at org.qbicc.plugin.dot.DotGenerator.process(DotGenerator.java:100)
	at org.qbicc.plugin.dot.DotGenerator.visitUnknown(DotGenerator.java:71)
	at org.qbicc.plugin.dot.DotGenerator.visitUnknown(DotGenerator.java:34)
	at org.qbicc.type.definition.element.ElementVisitor.visit(ElementVisitor.java:36)
	at org.qbicc.type.definition.element.MethodElement.accept(MethodElement.java:69)
	at org.qbicc.driver.ElementVisitorAdapter.accept(ElementVisitorAdapter.java:21)
	at org.qbicc.driver.ElementVisitorAdapter.accept(ElementVisitorAdapter.java:12)
	at org.qbicc.driver.Driver.lambda$execute0$5(Driver.java:377)
	at org.qbicc.driver.CompilationContextImpl.lambda$processQueue$7(CompilationContextImpl.java:691)
	at org.qbicc.driver.CompilationContextImpl$1.run(CompilationContextImpl.java:592)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ashu-mehra** [comment]
@galderz this should be resolved now. Can you please verify.

**Comment by galderz** [comment]
Yeah it works now, closing.
