### ISSUE TITLE
`get_nativeObjectMonitor` intrinsic ClassCastException

### ISSUE THREAD

**Issue by galderz** [qbicc/qbicc#809]
Latest main fails to compile with a failure early on:

```
[E] (org.qbicc.driver) ADD: An exception was thrown in an element handler: java.lang.ClassCastException: class org.qbicc.type.ReferenceType cannot be cast to class org.qbicc.type.PointerType (org.qbicc.type.ReferenceType and org.qbicc.type.PointerType are in unnamed module of loader 'app')
	at org.qbicc.plugin.intrinsics.core.CoreIntrinsics.lambda$registerOrgQbiccObjectModelIntrinsics$118(CoreIntrinsics.java:1718)
	at org.qbicc.plugin.intrinsics.IntrinsicBasicBlockBuilder.call(IntrinsicBasicBlockBuilder.java:54)
	at org.qbicc.type.definition.classfile.MethodParser.processNewBlock(MethodParser.java:1551)
	at org.qbicc.type.definition.classfile.MethodParser.processIf(MethodParser.java:1938)
	at org.qbicc.type.definition.classfile.MethodParser.processNewBlock(MethodParser.java:1747)
	at org.qbicc.type.definition.classfile.ClassFileImpl.createMethodBody(ClassFileImpl.java:1439)
	at org.qbicc.type.definition.element.InvokableElement.tryCreateMethodBody(InvokableElement.java:116)
	at org.qbicc.driver.ElementBodyCreator.accept(ElementBodyCreator.java:19)
	at org.qbicc.driver.ElementBodyCreator.accept(ElementBodyCreator.java:10)
	at org.qbicc.driver.Driver.lambda$execute0$6(Driver.java:355)
	at org.qbicc.driver.CompilationContextImpl.lambda$processQueue$7(CompilationContextImpl.java:769)
	at org.qbicc.main.Main.lambda$call0$3(Main.java:355)
	at org.qbicc.interpreter.Vm.doAttached(Vm.java:59)
	at org.qbicc.main.Main.lambda$call0$4(Main.java:355)
	at org.qbicc.driver.CompilationContextImpl$1.run(CompilationContextImpl.java:659)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Env:

```
❯ uname -a
Linux leo 5.11.15-300.fc34.x86_64 #1 SMP Fri Apr 16 13:41:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by galderz** [comment]
Does not longer appear after rebuilding all the bits.
