### ISSUE TITLE
libunwind development package presence should be checked earlier

### ISSUE THREAD

**Issue by galderz** [qbicc/qbicc#811]
Not having `libunwind-devel` installed caused initially this to happen when compiling code:

```
[E] (org.qbicc.driver) ADD: An exception was thrown in an element handler: java.lang.IllegalStateException: Object layout has not yet taken place
	at org.qbicc.type.ClassObjectType.getSize(ClassObjectType.java:37)
	at org.qbicc.plugin.intrinsics.core.CoreIntrinsics.lambda$registerOrgQbiccRuntimeCNativeIntrinsics$76(CoreIntrinsics.java:1292)
	at org.qbicc.plugin.intrinsics.IntrinsicBasicBlockBuilder.call(IntrinsicBasicBlockBuilder.java:54)
	at org.qbicc.type.definition.classfile.MethodParser.processNewBlock(MethodParser.java:1551)
	at org.qbicc.type.definition.classfile.ClassFileImpl.createMethodBody(ClassFileImpl.java:1439)
	at org.qbicc.type.definition.element.InvokableElement.tryCreateMethodBody(InvokableElement.java:116)
	at org.qbicc.driver.ElementBodyCreator.accept(ElementBodyCreator.java:19)
	at org.qbicc.driver.ElementBodyCreator.accept(ElementBodyCreator.java:10)
	at org.qbicc.driver.Driver.lambda$execute0$6(Driver.java:355)
	at org.qbicc.driver.CompilationContextImpl.lambda$processQueue$7(CompilationContextImpl.java:769)
	at org.qbicc.main.Main.lambda$call0$3(Main.java:360)
	at org.qbicc.interpreter.Vm.doAttached(Vm.java:59)
	at org.qbicc.main.Main.lambda$call0$4(Main.java:360)
	at org.qbicc.driver.CompilationContextImpl$1.run(CompilationContextImpl.java:659)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

David made a quick fix (see https://github.com/qbicc/qbicc/pull/810/files) but then you'd get:

```
[E] (org.qbicc.driver) ADD: An exception was thrown in an element handler: java.lang.IllegalArgumentException: Parameter 'name' may not be null
    at io.smallrye.common.constraint.Assert.checkNotNullParamChecked(Assert.java:32)
    at io.smallrye.common.constraint.Assert.checkNotNullParam(Assert.java:26)
    at org.qbicc.object.Section.declareFunction(Section.java:190)
    at org.qbicc.plugin.native_.NativeBasicBlockBuilder.staticMethod(NativeBasicBlockBuilder.java:142)
    at org.qbicc.graph.DelegatingBasicBlockBuilder.staticMethod(DelegatingBasicBlockBuilder.java:192)
    at org.qbicc.plugin.verification.ClassLoadingBasicBlockBuilder.staticMethod(ClassLoadingBasicBlockBuilder.java:76)
    at org.qbicc.graph.DelegatingBasicBlockBuilder.staticMethod(DelegatingBasicBlockBuilder.java:192)
    at org.qbicc.graph.DelegatingBasicBlockBuilder.staticMethod(DelegatingBasicBlockBuilder.java:192)
    at org.qbicc.type.definition.classfile.MethodParser.processNewBlock(MethodParser.java:1538)
    at org.qbicc.type.definition.classfile.ClassFileImpl.createMethodBody(ClassFileImpl.java:1439)
    at org.qbicc.type.definition.element.InvokableElement.tryCreateMethodBody(InvokableElement.java:116)
    at org.qbicc.driver.ElementBodyCreator.accept(ElementBodyCreator.java:19)
    at org.qbicc.driver.ElementBodyCreator.accept(ElementBodyCreator.java:10)
    at org.qbicc.driver.Driver.lambda$execute0$6(Driver.java:355)
    at org.qbicc.driver.CompilationContextImpl.lambda$processQueue$7(CompilationContextImpl.java:769)
    at org.qbicc.main.Main.lambda$call0$3(Main.java:355)
    at org.qbicc.interpreter.Vm.doAttached(Vm.java:59)
    at org.qbicc.main.Main.lambda$call0$4(Main.java:355)
    at org.qbicc.driver.CompilationContextImpl$1.run(CompilationContextImpl.java:659)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

The `name` was null because this probe had failed:

```
#include <stddef.h>
#include <limits.h>
#if defined(UNW_LOCAL_ONLY)
#undef UNW_LOCAL_ONLY
#endif
#define UNW_LOCAL_ONLY
#include <libunwind.h>
#if defined(QBICC_PASTE1)
#undef QBICC_PASTE1
#endif
#define QBICC_PASTE1(x) #x
#if defined(QBICC_PASTE2)
#undef QBICC_PASTE2
#endif
#define QBICC_PASTE2(x) QBICC_PASTE1(x)
typedef char char_array[];
char_array fn_name0 = QBICC_PASTE2(unw_getcontext());
unsigned long fn_name_size0 = sizeof(fn_name0);
```

The error reported at the very end was, but it was hidden with all the exceptions popping (the one about the name and all the rest that said that interpreter had compiler errors):

```
<stdin>: error: C Tool Chain: libunwind.h: No such file or directory
compilation terminated.
```

**Comment by galderz** [comment]
For context, see this [zulip message](https://qbicc.zulipchat.com/#narrow/stream/284393-qbicc-development/topic/Newbie's.20lair/near/261260291) and follow up discussion.
